### PR TITLE
Update to Ruby 2.4.4.

### PR DESCRIPTION
**Pull request by sbleon**

### CODE REVIEW

**Comment by sonnym** [comment]
It looks like `master` is already on `2.5.0`.

**Comment by sbleon** [comment]
Oh, awesome! I hadn't noticed.

Can you cut a new release?

**Comment by sonnym** [comment]
There have not been any functional, only developmental, changes since 29 August, so I do not see the need, but I am not fundamentally opposed.

**Comment by sonnym** [comment]
And to actually answer the question:  I can probably find some time to do so when I am in front of my computer.  I had actually tried adding a new gemfile for Rails 5.2, but had problems installing dependencies, so that project got nixed for the time being.

**Comment by sbleon** [comment]
The relaxing of the constraints to allow Rails 5.2 is the change that I'm
interested in.

**Comment by sonnym** [comment]
Ah, totally forgot about that!  Updated and released!  https://rubygems.org/gems/js-asset_paths/versions/0.4.4

**Comment by sbleon** [comment]
¡Muchas gracias!

**Pull request closed without merging**
