### PR TITLE
Allow to work with Rails 6.0.

### PR DESCRIPTION
**Pull request by sbleon**
No code changes were required to use this branch with one of my apps :-)

### CODE REVIEW

**Comment by sonnym** [comment]
Thanks for doing this!  The build is failing on travis - my guess would be that the gemfiles need to be updated using something like `appraisal update` (it's been a while since I've done this myself, so I'm not 100% on the details).  Please ping me when this is passing and I can merge it & cut a new release.  Thanks!

**Comment by sbleon** [comment]
Build is green!

**Comment by sonnym** [comment]
Awesome, thank you!

**Comment by sonnym** [comment]
Just cut a new release.  Thanks again!

**Comment by sbleon** [comment]
Awesome. Thanks so much!

**Pull request merged**
