### PR TITLE
Restore missing app/assets directory in packaged gem.

### PR DESCRIPTION
**Pull request by sbleon**

### CODE REVIEW

**Comment by sbleon** [comment]
I found one more missing file. I tested packaging it up locally and this seems to fix it.

**Comment by sonnym** [comment]
Thanks again.  I have been thinking recently (although I have not devoted any time to actual pursuit) about testing the packaging process itself, specifically to produce a minimum sufficient build.  If you have any thoughts/resource on the subject, I would love to look them over.

**Comment by sonnym** [comment]
https://rubygems.org/gems/js-asset_paths/versions/0.4.3

**Comment by sbleon** [comment]
Looks good. Thanks!

I'll let you know if I think of anything regarding to testing the packaging
process.

**Comment by sonnym** [comment]
To follow up on this, I came up with this approach for probing the contents of the generated `.gem` file as an extension of the standard `rake build` task provided by `rubygems`:  https://github.com/sonnym/js-asset_paths/commit/c03ba2dc0e5cf1ef15ac5097f4a5bfb6ca0a3882

It produces output like this when something is wrong (right now the only check is on the number of files, but that will catch the most egregious omissions):
```
$ rake build    
js-asset_paths 0.4.3 built to pkg/js-asset_paths-0.4.3.gem.                    
rake aborted!                          
Build contents are inconsistent:       
 LICENSE                               
 README.md                             
 app/assets/javascripts/js-asset_paths.js.erb                                  
 lib/js-asset_paths.rb                 
 lib/js_asset_paths.rb                 
 lib/js_asset_paths/engine.rb          
 lib/js_asset_paths/generator.rb       
 lib/js_asset_paths/version.rb         

/home/sonny/src/js-asset_paths/Rakefile:28:in `block (4 levels) in <top (required)>'                                                                           
/home/sonny/src/js-asset_paths/Rakefile:24:in `block (3 levels) in <top (required)>'                                                                           
/home/sonny/src/js-asset_paths/Rakefile:21:in `block (2 levels) in <top (required)>'                                                                           
/home/sonny/src/js-asset_paths/Rakefile:20:in `open'                           
/home/sonny/src/js-asset_paths/Rakefile:20:in `block in <top (required)>'      
Tasks: TOP => build                    
(See full trace by running task with --trace)
```

**Comment by sbleon** [comment]
Cool!

**Pull request merged**
